server:
  port: 8087

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/bookmanager?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    ip: localhost
    port: 3306
    database: bookmanager
  jpa:
#    hibernate.ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5

  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
com:
  liangliang:
    custom:
      windows-path: d:/liangliang/
      linux-path: /liangliang
      images-path: file:d:/liangliang/     #访问外部静态文件的路径



