server:
  port: 8087

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: 12345678
    url: jdbc:oracle:thin:@127.0.0.1:1521:bookmanager
    ip: localhost
    port: 1521
    database: bookmanager

  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5

  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liangliang.bookmanager.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

com:
  liangliang:
    custom:
      windows-path: d:/liangliang/
      linux-path: /liangliang
      images-path: file:d:/liangliang/     #访问外部静态文件的路径



