server:
  port: 8087
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bookmanager-hibernate?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    ip: localhost
    port: 3306
    database: bookmanager
  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
com:
  liangliang:
    custom:
      windows-path: d:/liangliang/
      linux-path: /liangliang
      images-path: file:d:/liangliang/     #访问外部静态文件的路径



